#MySQL
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    #spring.jpa.show-sql: true

